Add MACOSX_DEPLOYMENT_TARGET=10.12 env var for macOS build
```log
  + delocate-wheel --require-archs x86_64 -w /private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/repaired_wheel -v /private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/built_wheel/copium-0.1.0-cp310-cp310-macosx_10_9_x86_64.whl
  Fixing: /private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/built_wheel/copium-0.1.0-cp310-cp310-macosx_10_9_x86_64.whl
  Traceback (most recent call last):
    File "/private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/build/venv/bin/delocate-wheel", line 10, in <module>
      sys.exit(main())
    File "/private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/delocate/cmd/delocate_wheel.py", line 115, in main
      copied = delocate_wheel(
    File "/private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/delocate/delocating.py", line 1106, in delocate_wheel
      out_wheel_fixed = _check_and_update_wheel_name(
    File "/private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/delocate/delocating.py", line 928, in _check_and_update_wheel_name
      raise DelocationError(
  delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.9:
  /private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/tmpdlxubq52/wheel/copium/__init__.cpython-310-darwin.so has a minimum target of 10.12
  Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=10.12' to update minimum supported macOS for this wheel.
```