Rewrite copium in Rust (#39)
* Initial commit for Rust rewrite

* Fix segfaults

* Passes all tests on 3.14

* Add _copium.pth file

* Use types.rs everywhere

* Rename C implementation package to ccopium

* Add likely/unlikely intrinsics

* Move C src to ./ccopium

* Move Rust src to the project root

* Combine type check and casting

* Fix C build

* Preserve atomics short circuit behavior

* Add likely/unlikely to dict_iter

* Adapt tests to Rust implementation

* Remove bare apply() usage claim

Not sure if I want to make it documented just yet.

* Update configure mentions in the warning

* Remove stdlib atomics from pre-memo short circuit

* Remove unused directory

* Use real PyFunction_SetVectorcall on 3.12+

* Use `c_ulong` instead of `u64` for `tp_flags`

* Add MACOSX_DEPLOYMENT_TARGET=10.12 env var for macOS build

```log
  + delocate-wheel --require-archs x86_64 -w /private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/repaired_wheel -v /private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/built_wheel/copium-0.1.0-cp310-cp310-macosx_10_9_x86_64.whl
  Fixing: /private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/built_wheel/copium-0.1.0-cp310-cp310-macosx_10_9_x86_64.whl
  Traceback (most recent call last):
    File "/private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/build/venv/bin/delocate-wheel", line 10, in <module>
      sys.exit(main())
    File "/private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/delocate/cmd/delocate_wheel.py", line 115, in main
      copied = delocate_wheel(
    File "/private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/delocate/delocating.py", line 1106, in delocate_wheel
      out_wheel_fixed = _check_and_update_wheel_name(
    File "/private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/cibw-run-fnbn0eoz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/delocate/delocating.py", line 928, in _check_and_update_wheel_name
      raise DelocationError(
  delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.9:
  /private/var/folders/yj/mflq9j197hz47cqbjv17r7k00000gn/T/tmpdlxubq52/wheel/copium/__init__.cpython-310-darwin.so has a minimum target of 10.12
  Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=10.12' to update minimum supported macOS for this wheel.
```

* Fix tests/api typechecking

* Update cargo package name

* Fix linting errors

* Fix linking on Windows

* Remove `link(name = "pythonXY")` for Windows

* Fix Rust warnings 1/2

* Fix Rust warnings 2/2

* Fix crash on free-threading

* Fix GIL warning on free-threaded

* Use saved dict.items() vectorcall

* Add `__imp__Py_NoneStruct` extern for Windows

* Remove `__imp__Py_NoneStruct` extern for Windows

* Add pythonXY link attr for Windows

* Replace pythonXY link attr with actual Python version

* Use maturin-action

* Remove actions/setup-python

* Update cd-build.yaml

* Update cd-build.yaml

* Update cd-build.yaml

* Update cd-build.yaml

* Skip Python 3.10 and 3.11 builds on Windows 11 ARM

* Don't strip symbols on --release build

* Remove unnecessary and inline dict_iter on 3.14

* Optimize stack handling

* Rename lib to copium

* Add a proper test for retention policy

* Fix STACK_LOW fallback pointer

* Fix unclosed bracket

* Use #[inline(always)] on memo.table.insert_h

* Loosen test_memo_reused